# Generated by Django 5.2.10 on 2026-04-14 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_order_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cod', 'Cash on Delivery'), ('esewa', 'eSewa'), ('paypal', 'PayPal'), ('card', 'Credit/Debit Card')], default='cod', max_length=20),
        ),
    ]
