# Generated by Django 5.2.10 on 2026-04-14 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_alter_order_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='image_url',
            field=models.URLField(blank=True, help_text='External image URL (fallback if no image uploaded)', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='promotions/'),
        ),
    ]
