# Generated by Django 5.2.10 on 2026-05-16 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_order_user_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='shipping_info',
            field=models.CharField(default='Free Fast Delivery', max_length=200),
        ),
        migrations.AddField(
            model_name='product',
            name='warranty_info',
            field=models.CharField(default='2 Year Warranty', max_length=200),
        ),
        migrations.AlterField(
            model_name='order',
            name='country',
            field=models.CharField(default='Nepal', max_length=100),
        ),
    ]
