# Generated by Django 5.2.10 on 2026-07-04 17:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_product_shipping_info_product_warranty_info_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cod', 'Cash on Delivery'), ('esewa', 'eSewa'), ('paypal', 'PayPal'), ('card', 'Credit/Debit Card'), ('whatsapp', 'WhatsApp Inquiry')], default='cod', max_length=20),
        ),
        migrations.CreateModel(
            name='CashClosing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_type', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('custom', 'Custom Range')], default='daily', max_length=10)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('opening_cash', models.DecimalField(decimal_places=2, default=0.0, help_text='Cash in drawer at start of period', max_digits=10)),
                ('total_cash_sales', models.DecimalField(decimal_places=2, default=0.0, help_text='Total cash collected from sales (COD orders)', max_digits=10)),
                ('total_expenses', models.DecimalField(decimal_places=2, default=0.0, help_text='Total expenses in this period', max_digits=10)),
                ('expected_closing_cash', models.DecimalField(decimal_places=2, default=0.0, help_text='Opening + Sales - Expenses', max_digits=10)),
                ('actual_closing_cash', models.DecimalField(decimal_places=2, default=0.0, help_text='Cash physically counted in drawer', max_digits=10)),
                ('discrepancy', models.DecimalField(decimal_places=2, default=0.0, help_text='Actual - Expected (positive=over, negative=short)', max_digits=10)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_closings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.CharField(choices=[('rent', 'Rent'), ('salary', 'Salary / Wages'), ('utilities', 'Utilities (Electric, Water, Internet)'), ('supplies', 'Office / Shop Supplies'), ('repairs', 'Repairs & Maintenance'), ('transport', 'Transport / Delivery'), ('marketing', 'Marketing & Advertising'), ('other', 'Other')], default='other', max_length=20)),
                ('date', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
